name: CI-CD

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout do Repositório"
      uses: actions/checkout@v4.1.2
    
    - name: "Autenticação no docker"
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: "Construção da Imagem Docker"
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: .src/Dockerfile
        push: true
        tags: joaohcca/devops4devs-news:latest joaohcca/devops4devs-news:${{ github.run_number }}	

  CD:
    needs: ["CI"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4.1.2
      
      - name: "Configuração do ambiente AWS"
        uses: aws-action/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_kEY }}
      
      - name: Configuração do kubeconfig
        run: echo aws eks update-kubeconfig --name devops4devs-eks --region us-east-1
      - name: Atualização do manifesto
        shell: bash
        run: |
          sed -i "s/{{AWS_ACESS_KEY}}/${{ secrets.AWS_ACCESS_KEY }}/G" .k8s/deployment.yaml
          sed -i "s/{{AWS_SECRET_kEY}}/${{ secrets.AWS_SECRET_kEY }}/G" .k8s/deployment.yaml				
      - name: "Executar o deploy"
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./k8s/depoloyment.yaml
          images: |
            joaohcca/devops4devs-news:${{ github.run_number }}